name: Action  # Use tags to trigger the action
on:
  workflow_dispatch:
    inputs:
      statement:
        description: Question
        required: true
        default: "\"How is the weather?\""
jobs:
  app-build: 
    name: ELIZA build on Ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & Set Environment Variables
        uses: actions/checkout@v3
        
      - name: Qustion ELIZA ${{ inputs.statement }} 
        run: |
          cd $GITHUB_WORKSPACE
          python action.py --statement ${{ inputs.statement }} >> answer_sheet.txt

      - name: ELIZA Answer $GITHUB_ENV
        run: |
          echo "::group:: Result"
          echo "Q: ${{ inputs.statement }}"
          echo "A: $(cat answer_sheet.txt)"
      
